
// src/lib/enemies.ts
import type { EnemyUnit } from '@/types';

// This file contains the base definitions for enemy units that can be generated as defenders.

export const BASE_ENEMY_UNITS: EnemyUnit[] = [
  // HUMAINS
  {
    id: 'human-guard',
    name: 'Garde Humain',
    race: 'Humain',
    class: 'Guerrier',
    level: 1,
    hitPoints: 11,
    armorClass: 16,
    attackBonus: 3,
    damage: '1d6+1',
    portraitUrl: null,
    expValue: 25,
    goldValue: 5,
    lootTable: [{ itemId: 'weap-018', dropChance: 0.1 }],
  },
  {
    id: 'human-archer',
    name: 'Archer Humain',
    race: 'Humain',
    class: 'Archer',
    level: 1,
    hitPoints: 9,
    armorClass: 14,
    attackBonus: 4,
    damage: '1d6+2',
    portraitUrl: null,
    expValue: 25,
    goldValue: 5,
    lootTable: [{ itemId: 'weap-012', dropChance: 0.1 }],
  },
  {
    id: 'human-captain',
    name: 'Capitaine Humain',
    race: 'Humain',
    class: 'Guerrier',
    level: 3,
    hitPoints: 22,
    armorClass: 17,
    attackBonus: 5,
    damage: '1d8+2',
    portraitUrl: null,
    expValue: 75,
    goldValue: 20,
    lootTable: [{ itemId: 'weap-019', dropChance: 0.2 }, { itemId: 'arm-005', dropChance: 0.1 }],
  },

  // GOBELINS
  {
    id: 'goblin-warrior',
    name: 'Guerrier Gobelin',
    race: 'Gobelin',
    class: 'Guerrier',
    level: 1,
    hitPoints: 7,
    armorClass: 13,
    attackBonus: 2,
    damage: '1d6',
    portraitUrl: null,
    expValue: 20,
    goldValue: 3,
    lootTable: [{ itemId: 'weap-015', dropChance: 0.05 }],
  },
  {
    id: 'goblin-shaman',
    name: 'Shaman Gobelin',
    race: 'Gobelin',
    class: 'Mage',
    level: 2,
    hitPoints: 10,
    armorClass: 12,
    attackBonus: 1,
    damage: '1d4', // Assuming a weak physical attack, spell damage would be separate
    portraitUrl: null,
    expValue: 50,
    goldValue: 10,
    lootTable: [{ itemId: 'cons-combat-heal-Commun', dropChance: 0.1 }],
  },
  
  // ELFE
  {
    id: 'elf-archer',
    name: 'Archer Elfe',
    race: 'Elfe',
    class: 'Archer',
    level: 2,
    hitPoints: 15,
    armorClass: 15,
    attackBonus: 5,
    damage: '1d8+3',
    portraitUrl: null,
    expValue: 60,
    goldValue: 15,
    lootTable: [{ itemId: 'weap-035', dropChance: 0.1 }],
  },
   {
    id: 'elf-bladedancer',
    name: 'Danseur de Lames Elfe',
    race: 'Elfe',
    class: 'Guerrier',
    level: 3,
    hitPoints: 25,
    armorClass: 16,
    attackBonus: 6,
    damage: '2d4+3',
    portraitUrl: null,
    expValue: 100,
    goldValue: 30,
    lootTable: [{ itemId: 'weap-031', dropChance: 0.15 }],
  },
];
