
import type { BaseItem } from '@/types';

export const BASE_WEAPONS: BaseItem[] = [
  { id: 'weap-001', name: 'Bâton', description: 'Un simple bâton de bois, utile pour la marche et pour se défendre.', type: 'weapon', damage: '1d6', baseGoldValue: 2, universe: 'Médiéval-Fantastique' },
  { id: 'weap-002', name: 'Dague', description: 'Une lame courte et rapide, facile à dissimuler.', type: 'weapon', damage: '1d4', baseGoldValue: 2, universe: 'Médiéval-Fantastique' },
  { id: 'weap-003', name: 'Gourdin', description: 'Une arme contondante simple mais efficace.', type: 'weapon', damage: '1d4', baseGoldValue: 1, universe: 'Médiéval-Fantastique' },
  { id: 'weap-004', name: 'Hachette', description: 'Une petite hache polyvalente, pour couper du bois ou des ennemis.', type: 'weapon', damage: '1d4', baseGoldValue: 5, universe: 'Médiéval-Fantastique' },
  { id: 'weap-005', name: 'Javeline', description: 'Une lance légère conçue pour être lancée.', type: 'weapon', damage: '1d4', baseGoldValue: 5, universe: 'Médiéval-Fantastique' },
  { id: 'weap-006', name: 'Lance', description: 'Une arme d\'hast avec une bonne allonge.', type: 'weapon', damage: '1d4', baseGoldValue: 1, universe: 'Médiéval-Fantastique' },
  { id: 'weap-007', name: 'Marteau léger', description: 'Un marteau de guerre maniable.', type: 'weapon', damage: '1d4', baseGoldValue: 2, universe: 'Médiéval-Fantastique' },
  { id: 'weap-008', name: 'Masse d\'armes', description: 'Une arme contondante conçue pour écraser les armures.', type: 'weapon', damage: '1d4', baseGoldValue: 5, universe: 'Médiéval-Fantastique' },
  { id: 'weap-009', name: 'Massue', description: 'Un gourdin plus lourd et plus menaçant.', type: 'weapon', damage: '1d4', baseGoldValue: 2, universe: 'Médiéval-Fantastique' },
  { id: 'weap-010', name: 'Serpe', description: 'Une lame incurvée, initialement un outil agricole.', type: 'weapon', damage: '1d4', baseGoldValue: 1, universe: 'Médiéval-Fantastique' },
  { id: 'weap-011', name: 'Arbalète légère', description: 'Une arbalète facile à recharger mais moins puissante que sa version lourde.', type: 'weapon', damage: '1d6', baseGoldValue: 25, universe: 'Médiéval-Fantastique' },
  { id: 'weap-012', name: 'Arc court', description: 'Un arc simple pour les tireurs d\'élite mobiles.', type: 'weapon', damage: '1d6', baseGoldValue: 25, universe: 'Médiéval-Fantastique' },
  { id: 'weap-013', name: 'Fléchette', description: 'Une petite arme de lancer, souvent enduite de poison.', type: 'weapon', damage: '1d4', baseGoldValue: 5, universe: 'Médiéval-Fantastique' },
  { id: 'weap-014', name: 'Fronde', description: 'Une arme simple pour lancer des projectiles contondants.', type: 'weapon', damage: '1d4', baseGoldValue: 1, universe: 'Médiéval-Fantastique' },
  { id: 'weap-015', name: 'Cimeterre', description: 'Une épée à lame courbe, prisée pour ses coups tranchants.', type: 'weapon', damage: '1d6', baseGoldValue: 25, universe: 'Médiéval-Fantastique' },
  { id: 'weap-016', name: 'Coutille', description: 'Une arme d\'hast avec une lame de hache et une pointe de lance.', type: 'weapon', damage: '1d6', baseGoldValue: 20, universe: 'Médiéval-Fantastique' },
  { id: 'weap-017', name: 'Épée à deux mains', description: 'Une immense épée nécessitant les deux mains pour être maniée.', type: 'weapon', damage: '1d9', baseGoldValue: 50, universe: 'Médiéval-Fantastique' },
  { id: 'weap-018', name: 'Épée courte', description: 'Une lame droite et fiable pour le combat rapproché.', type: 'weapon', damage: '1d5', baseGoldValue: 10, universe: 'Médiéval-Fantastique' },
  { id: 'weap-019', name: 'Épée longue', description: 'L\'arme de prédilection de nombreux chevaliers et aventuriers.', type: 'weapon', damage: '1d5', baseGoldValue: 15, universe: 'Médiéval-Fantastique' },
  { id: 'weap-020', name: 'Fléau d\'armes', description: 'Une arme composée d\'une tête cloutée reliée à un manche par une chaîne.', type: 'weapon', damage: '1d5', baseGoldValue: 10, universe: 'Médiéval-Fantastique' },
  { id: 'weap-021', name: 'Fouet', description: 'Une arme exotique capable de désarmer ou de frapper à distance.', type: 'weapon', damage: '1d4', baseGoldValue: 2, universe: 'Médiéval-Fantastique' },
  { id: 'weap-022', name: 'Hache à deux mains', description: 'Une hache massive capable de fendre un bouclier en deux.', type: 'weapon', damage: '1d6', baseGoldValue: 30, universe: 'Médiéval-Fantastique' },
  { id: 'weap-023', name: 'Hache d\'armes', description: 'Une hache de guerre équilibrée pour le combat à une main.', type: 'weapon', damage: '1d5', baseGoldValue: 10, universe: 'Médiéval-Fantastique' },
  { id: 'weap-024', name: 'Hallebarde', description: 'Une arme d\'hast polyvalente avec une pointe de lance et une lame de hache.', type: 'weapon', damage: '1d6', baseGoldValue: 20, universe: 'Médiéval-Fantastique' },
  { id: 'weap-025', name: 'Lance d’arçon', description: 'Une longue lance utilisée principalement à cheval.', type: 'weapon', damage: '1d5', baseGoldValue: 10, universe: 'Médiéval-Fantastique' },
  { id: 'weap-026', name: 'Maillet', description: 'Un grand marteau en bois, étonnamment efficace.', type: 'weapon', damage: '1d5', baseGoldValue: 10, universe: 'Médiéval-Fantastique' },
  { id: 'weap-027', name: 'Marteau de guerre', description: 'Conçu pour percer les armures les plus épaisses.', type: 'weapon', damage: '1d5', baseGoldValue: 15, universe: 'Médiéval-Fantastique' },
  { id: 'weap-028', name: 'Morgenstern', description: 'Une masse à pointes, terrifiante et brutale.', type: 'weapon', damage: '1d5', baseGoldValue: 15, universe: 'Médiéval-Fantastique' },
  { id: 'weap-029', name: 'Pic de guerre', description: 'Une arme conçue pour perforer les armures avec sa pointe acérée.', type: 'weapon', damage: '1d4', baseGoldValue: 5, universe: 'Médiéval-Fantastique' },
  { id: 'weap-030', name: 'Pique', description: 'Une très longue lance, idéale pour tenir les ennemis à distance.', type: 'weapon', damage: '1d4', baseGoldValue: 5, universe: 'Médiéval-Fantastique' },
  { id: 'weap-031', name: 'Rapière', description: 'Une épée fine et légère, parfaite pour l\'escrime et les coups d\'estoc.', type: 'weapon', damage: '1d6', baseGoldValue: 25, universe: 'Médiéval-Fantastique' },
  { id: 'weap-032', name: 'Trident', description: 'Une lance à trois pointes, aussi bien utilisée par les pêcheurs que par les gladiateurs.', type: 'weapon', damage: '1d4', baseGoldValue: 5, universe: 'Médiéval-Fantastique' },
  { id: 'weap-033', name: 'Arbalète de poing', description: 'Une petite arbalète qui peut être utilisée d\'une seule main.', type: 'weapon', damage: '2d5', baseGoldValue: 75, universe: 'Médiéval-Fantastique' },
  { id: 'weap-034', name: 'Arbalète lourde', description: 'Une arme puissante mais lente à recharger, capable de perforer des armures.', type: 'weapon', damage: '1d9', baseGoldValue: 50, universe: 'Médiéval-Fantastique' },
  { id: 'weap-035', name: 'Arc long', description: 'Un grand arc puissant qui demande de la force pour être utilisé efficacement.', type: 'weapon', damage: '1d9', baseGoldValue: 50, universe: 'Médiéval-Fantastique' },
  { id: 'weap-036', name: 'Filet', description: 'Une arme non létale utilisée pour entraver un adversaire.', type: 'weapon', damage: '1d4', baseGoldValue: 1, universe: 'Médiéval-Fantastique' },
  { id: 'weap-037', name: 'Sarbacane', description: 'Un tube utilisé pour souffler de petites fléchettes, souvent empoisonnées.', type: 'weapon', damage: '1d5', baseGoldValue: 10, universe: 'Médiéval-Fantastique' },
];

    